apiVersion: v1
kind: Pod
metadata:
  name: peer0
  labels:
    app: peer0
spec:
  containers:
  - name: algorand-container
    image: local/algorand-peer
    imagePullPolicy: Never
    command: ['server', '-peer', 'peer1:3001']
    ports:
    - name: peer0-client
      containerPort: 3000
    - name: peer0-algorand
      containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: peer0
spec:
  type: NodePort
  selector:
    app: peer0
  ports:
  - port: 3000
    targetPort: peer0-client
    name: client-port
  - port: 3001
    targetPort: peer0-algorand
    name: algorand-port

